# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6102f38665973ccea6fba563054a37798766e56eecb46f3114fe88e0ab59a8256b87c6e9d3067c976efe7ca2615c46488381db9792838b8d983d949bf9f4d8ca

test:
  secret_key_base: 7a0a581c7aef669bd7caec31fcceb8bbb557c52f4503d9049ab40756696e9e7025c94f4c600dd74133bcb13fd47209cc091a546236deac6ca9d194266fade8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
